### ISSUE TITLE
H5ss.exe has stoped working on start playing

### ISSUE THREAD

**Issue by MinChanSike** [linkingvision/h5stream#3]
Why it is stop working on start playing?

My source config is like this.
``` 
"source": {
  "src": [
   {
    "strNameComment": "name for this stream",
    "strName": "Test Camera",
    "strTokenComment": "token for this stream, must unique, if same, only frist will be available",
    "strToken": "officecam01",
    "nTypeComment": "source type H5_FILE/H5_STREAM",
    "nType": "H5_STREAM",
    "strUrlComment": "",
    "strUrl": "rtsp://192.168.0.156:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
    "strUserComment": "username",
    "strUser": "",
    "strPasswdComment": "password",
    "strPasswd": ""
   }
]
}
```
**Error**
![h5](https://user-images.githubusercontent.com/2868221/34194133-2c3ba33e-e592-11e7-9958-9d2a1843a538.png)

**Comment by xsmart** [comment]
You change the default token name in conf file need change in the html also , you can just change the url and user password, Wechat xsmart_veyesys Skype: xsmart@veyesys.com for more support.

**Comment by MinChanSike** [comment]
Yes, I do.
I also change at index.html but can not play it.
```
v1 = new H5sPlayerWS("h5sVideo1", "officecam01"); //at initialize

v1.connect("officecam01"); //at play/pause
```
By the way, my rtsp source is no need user-name and password.
So I left it _blank_. I was added source stream by REST.
Anything wrong? Thanks.

**Comment by xsmart** [comment]
Blank maybe has some issue, if server don’t need, just keep the default user and password.

**Comment by MinChanSike** [comment]
Although I set with REST with default user and password not working.
```
{
   "strName": "Office Camera 2",
   "strToken": "officecam01",
   "strUrl": "rtsp://192.168.0.156:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif",
   "strUser": "admin",
   "strPasswd": "12345"
}

**Comment by xsmart** [comment]
Change the ipc password to some , not blank.
