### ISSUE TITLE
cannot find h5slib

### ISSUE THREAD

**Issue by derzu** [linkingvision/h5stream#4]
Hi, 

I'm trying to compile on Linux Ubuntu 14.04. But the make process is stopped because:

/usr/bin/ld: cannot find -lh5slib

This happens when it's inside the h5stream-master/h5ss folder and try to to this compiling:
`g++ -o h5ss -std=c++11 -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DLINUX -Iinclude  -Wall -Wextra -Wshadow -Wformat-security -Winit-self -Wmissing-prototypes -O2 -DLINUX -Iinclude  -DUSE_WEBSOCKET -I/home/derzu/Downloads/h5stream-master/output/Ubuntu-14.04-64bit/include -I../h5slib/include -I./src/ -I./src/mse -I../3rdparty/live555//BasicUsageEnvironment/include  -I../3rdparty/live555//groupsock/include -I../3rdparty/live555//liveMedia/include -I../3rdparty/live555//UsageEnvironment/include -I../3rdparty/live555//live555/include/ -I../3rdparty/civetweb/include/ -DNDEBUG  out.linux/build//../3rdparty/civetweb/src/CivetServer.o out.linux/build//src/webserver.o out.linux/build//../3rdparty/civetweb/src/civetweb.o out.linux/build//src/h5ss.o  -lpthread -lm -lrt -ldl -L/home/derzu/Downloads/h5stream-master/output/Ubuntu-14.04-64bit/lib -llive555 -lh5slib -lavformat -lavcodec -lavutil -lswscale`

I looked at the h5slib folder, but it has just the header files and the binary files for windows. Can you add the cpp files or add an binary lib (.so) for Linux?

Best regards,

Derzu.

**Comment by xsmart** [comment]
you can use the prebuild version, some part of this project is not open source
https://www.linkingvision.com/download/H5Stream/

**Comment by derzu** [comment]
Thanks for the quick reply.

I try to compile with the libh5slib.so that is available at the link (www.linkingvision.com/download/H5Stream/archive/H5S-r1.0.1128.16-Ubuntu-16.04-64bit.tar.gz) but it's not compatible.

But I had success to run the binary version of the h5ss.

Thanks.
